--liquibase formatted sql

--changeset codex:055-extend-game-systems
-- Системы не только на d20: мастер ищет стол по той, в которую играет, а
-- HOMEBREW закрывает всё, чего нет в списке, — название тогда пишется в игре.
insert into game_systems (code, name)
values ('DND_4E', 'D&D 4'),
       ('DND_35', 'D&D 3.5'),
       ('ADND', 'AD&D'),
       ('PATHFINDER_1E', 'Pathfinder 1e'),
       ('PATHFINDER_2E', 'Pathfinder 2e'),
       ('STARFINDER', 'Starfinder'),
       ('LEVEL_UP_A5E', 'Level Up: Advanced 5th Edition'),
       ('TALES_OF_THE_VALIANT', 'Tales of the Valiant'),
       ('THIRTEENTH_AGE', '13th Age'),
       ('DRAGONBANE', 'Dragonbane'),
       ('DAGGERHEART', 'Daggerheart'),
       ('OSE', 'Old-School Essentials'),
       ('DCC', 'Dungeon Crawl Classics'),
       ('SHADOWDARK', 'Shadowdark'),
       ('MORK_BORG', 'Mörk Borg'),
       ('CAIRN', 'Cairn'),
       ('KNAVE', 'Knave'),
       ('MOTHERSHIP', 'Mothership'),
       ('CALL_OF_CTHULHU', 'Call of Cthulhu'),
       ('DELTA_GREEN', 'Delta Green'),
       ('TRAIL_OF_CTHULHU', 'Trail of Cthulhu'),
       ('KULT', 'Kult: Divinity Lost'),
       ('VAESEN', 'Vaesen'),
       ('ALIEN_RPG', 'Alien RPG'),
       ('DREAD', 'Dread'),
       ('VAMPIRE_MASQUERADE', 'Vampire: The Masquerade'),
       ('WEREWOLF_APOCALYPSE', 'Werewolf: The Apocalypse'),
       ('MAGE_ASCENSION', 'Mage: The Ascension'),
       ('HUNTER_RECKONING', 'Hunter: The Reckoning'),
       ('CHRONICLES_OF_DARKNESS', 'Chronicles of Darkness'),
       ('CYBERPUNK_RED', 'Cyberpunk RED'),
       ('CYBERPUNK_2020', 'Cyberpunk 2020'),
       ('SHADOWRUN', 'Shadowrun'),
       ('STAR_WARS_FFG', 'Star Wars (FFG)'),
       ('STAR_TREK_ADVENTURES', 'Star Trek Adventures'),
       ('TRAVELLER', 'Traveller'),
       ('LANCER', 'Lancer'),
       ('CORIOLIS', 'Coriolis'),
       ('STARFORGED', 'Ironsworn: Starforged'),
       ('PARANOIA', 'Paranoia'),
       ('BLADE_RUNNER', 'Blade Runner RPG'),
       ('TWILIGHT_2000', 'Twilight: 2000'),
       ('MUTANT_YEAR_ZERO', 'Mutant: Year Zero'),
       ('WFRP', 'Warhammer Fantasy Roleplay'),
       ('WARHAMMER_40K', 'Warhammer 40,000 Roleplay'),
       ('THE_ONE_RING', 'The One Ring'),
       ('FORBIDDEN_LANDS', 'Forbidden Lands'),
       ('SYMBAROUM', 'Symbaroum'),
       ('RUNEQUEST', 'RuneQuest'),
       ('PENDRAGON', 'Pendragon'),
       ('LEGEND_OF_FIVE_RINGS', 'Legend of the Five Rings'),
       ('SEVENTH_SEA', '7th Sea'),
       ('IRONSWORN', 'Ironsworn'),
       ('AVATAR_LEGENDS', 'Avatar Legends'),
       ('FATE_CORE', 'Fate Core'),
       ('FATE_ACCELERATED', 'Fate Accelerated'),
       ('GURPS', 'GURPS'),
       ('SAVAGE_WORLDS', 'Savage Worlds'),
       ('CYPHER_SYSTEM', 'Cypher System (Numenera)'),
       ('GENESYS', 'Genesys'),
       ('BASIC_ROLEPLAYING', 'Basic Roleplaying'),
       ('TINY_D6', 'Tiny d6'),
       ('MUTANTS_MASTERMINDS', 'Mutants & Masterminds'),
       ('MARVEL_MULTIVERSE', 'Marvel Multiverse RPG'),
       ('BLADES_IN_THE_DARK', 'Blades in the Dark'),
       ('APOCALYPSE_WORLD', 'Apocalypse World'),
       ('DUNGEON_WORLD', 'Dungeon World'),
       ('MONSTER_OF_THE_WEEK', 'Monster of the Week'),
       ('MASKS', 'Masks: A New Generation'),
       ('BURNING_WHEEL', 'Burning Wheel'),
       ('KIDS_ON_BIKES', 'Kids on Bikes'),
       ('HOMEBREW', 'Своя система')
on conflict (code) do nothing;

-- Название своей системы. Заполнено только у HOMEBREW — это держит сервис.
alter table games
    add column custom_system varchar(120);

--rollback alter table games drop column custom_system;
